<?php

namespace medic\PatientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExamenPatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenPatientRepository extends EntityRepository
{
}
