<?php

namespace medic\PatientBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends EntityRepository
{
  public function getPatients()
  {
    $query = $this->createQueryBuilder('a')
      ->orderBy('a.nom', 'ASC')
      ->addOrderBy('a.prenom', 'ASC')
      ->getQuery();
      
    return $query->getResult();
  }
  
  public function getAge($monPatient)
  {
    $naissance = $monPatient['monPatient'][0]->getDateNaissance();
    if ($naissance == null)
        return '';
    $annee =  $naissance->format('Y-m-d H:i:s');
    
    
    $arr1 = explode('-',$annee);
    $arr2 = explode('/', date('Y/m/d'));
    
    if (($arr1[1] < $arr2[1]) || ($arr1[1] == $arr2[1]) && ($arr1[2] <= $arr2[2]))
        $age = intval($arr2[0]) - intval($arr1[0]);
    else
        $age = intval($arr2[0]) - intval($arr1[0]) - 1;
    
    
    return $age.' ans';
  }
  
  public function trouveId($monPatient)
  {
    $id = $monPatient['monPatient'][0]->getId();
    
    $session = new Session();
    $session->set('name', $id);
    $essai = $session->get('name');
    
    return $id;
  }

}
