<?php

namespace medic\SymptomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SymptomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymptomeRepository extends EntityRepository
{
}
