<?php

namespace medic\SubstanceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubstanceRepository extends EntityRepository
{
}
